apiVersion: apps/v1
kind: Deployment
metadata:
  name: staticws4rws
  labels:
    app: staticws4rws
spec:
  selector:
    matchLabels:
      app: staticws4rws
  replicas: 1
  template:
    metadata:
      labels:
        app: staticws4rws
    spec:
      containers:
      - name: staticws4rws
        imagePullPolicy: Always
        image: sim007/staticws4rws
        #image: simcontainers.azurecr.io/sim007/staticws4rws
        resources:
        ports:
        - containerPort: 80
---        
apiVersion: v1       
kind: Service
metadata:
  name: staticws4rws
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: staticws4rws