apiVersion: apps/v1
kind: Deployment
metadata:
  name: staticws4rws-deployment
  labels:
    app: staticws4rws
spec:
  replicas: 2
  selector:
    matchLabels:
      app: staticws4rws
  template:
    metadata:
      labels:
        app: staticws4rws
    spec:
      containers:
      - name: staticws4rws
        image: sim007/staticws4rws
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---             
apiVersion: v1       
kind: Service
metadata:
  name: staticws4rws
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: staticws4rws